controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: position_controllers/GripperActionController
    joint_state_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5

    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
      
gripper_controller:
  ros__parameters:
    joint: Gripper
    goal_tolerance: 0.1

    command_interfaces:
      - position

    state_interfaces:
      - position