#goal definition
string[] goal_states
BBMessage bb_message
# string id
# geometry_msgs/Point pose
string command
string tree

---
#result definition
string error_string
bool success
---
#feedback
float64 progress_rate
float64 success_prospect
string feedback